version: '3'

services:
  springboot3awssqs:
    image: springboot3awssqs:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - R2DBC_URL=r2dbc:pool:postgres://host.docker.internal:5432/postgres
      - R2DBC_USER=postgres
      - R2DBC_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - AWS_ACCESS_KEY=ACCESSKEY
      - AWS_SECRET_KEY=SECRETKEY
      - AWS_REGION=us-east-1
      - SQS_QUEUE_NAME=sqs-demo.fifo
      - SQS_QUEUE_REGION=us-east-1
    deploy:
      mode: replicated
      replicas: 3