spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres
    locations: classpath:db/migration
  cloud:
    aws:
      credentials:
        access-key: ACCESSKEY
        secret-key: SECRETKEY
      region:
        static: us-east-1
sqs:
  notifications:
    queue:
      name: queue
      region: us-east-1



